# Generated by Django 4.0.7 on 2024-05-05 15:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('banned', 'BANNED'), ('completed', 'COMPLETED'), ('new', 'NEW')], default='active', max_length=100),
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 15, 0, 41, 471888, tzinfo=utc))),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('banned', 'BANNED'), ('completed', 'COMPLETED'), ('new', 'NEW')], default='new', max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
